export const GET_DETAILLIST = 'GET_DETAILLIST'
export const SAVE_RECORDID = 'SAVE_RECORDID'
export const GET_USERINFO = 'GET_USERINFO'
export const SAVE_USERLIKE = 'SAVE_USERLIKE'
export const SAVE_MOVIENAME = 'SAVE_MOVIENAME'
export const DEL_USERLIKE = 'DEL_USERLIKE'

